/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#pragma warning disable IDE0044, IDE0049, IDE0055, IDE1006,
#pragma warning disable SA1004, SA1008, SA1023, SA1028,
#pragma warning disable SA1121, SA1134,
#pragma warning disable SA1201,
#pragma warning disable SA1300, SA1306, SA1307, SA1310, SA1313,
#pragma warning disable SA1500, SA1505, SA1507,
#pragma warning disable SA1600, SA1601, SA1604, SA1605, SA1611, SA1615, SA1649,

namespace Pincushion {
using System;
using System.Runtime.InteropServices;

public unsafe partial class Ffi {
#if IOS
    private const string RustLib = "pincushion.framework/pincushion";
#else
    private const string RustLib = "pincushion";
#endif
}

public unsafe partial class Ffi {
    /// <summary>
    /// - <c>volume</c>: The volume of the mesh, assumed to be in meters squared.
    /// - <c>points_per_cm</c>: The number of points per centimeter.
    ///
    /// Returns: The number of points that should be sampled.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    UIntPtr get_num_points_ffi (
        float volume,
        float points_per_cm);
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_float_t {
    public float * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_size_t {
    public UIntPtr * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

public unsafe partial class Ffi {
    /// <summary>
    /// - <c>vertices</c>: The vertices as a flat slice of coordinates.
    /// - <c>triangles</c>: The triangles as a flat slice of indices.
    ///
    /// Returns: The volume of the mesh.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    float get_volume_ffi (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Sample random points on the mesh.
    ///
    /// - <c>vertices</c>: The vertices as a flat slice of coordinates.
    /// - <c>triangles</c>: The triangles as a flat slice of indices.
    /// - <c>points</c>: A pre-defined flat slice of coordinates.
    /// This will be filled with the sampled points.
    /// This must be defined on the other side of the FFI boundary.
    /// To get the expected size of <c>points</c>, call <c>get_volume_ffi(vertices, triangles)</c> followed by <c>get_num_points_ffi(volume, points_per_cm)</c>
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void sample_points_ffi (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles,
        Vec_float_t * points);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Sample points on a mesh, given a density of points and a pre-defined slice to fill.
    ///
    /// - <c>vertices</c>: The vertices as a flat slice of coordinates.
    /// - <c>triangles</c>: The triangles as a flat slice of indices.
    /// - <c>points_per_cm</c>: The number of points per centimeter.
    /// - <c>points</c> A predefined flat slice of coordinates.
    /// This will be filled with the sampled points.
    /// The number of points, as derived from <c>points_per_cm</c>, can be more than <c>points.len()</c>.
    /// If this happens, the entirety of <c>points</c> will be filled, resulting in no error.
    /// The number of points can also be less than <c>points.len()</c>.
    /// If this happens, a slice of <c>points</c> is filled.
    ///
    /// Returns: The number of sampled points (the size of the <c>points</c> sub-slice).
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    UIntPtr sample_points_ffi_from_ppcm (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles,
        float points_per_cm,
        Vec_float_t * points);
}


} /* Pincushion */
