/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#pragma warning disable IDE0044, IDE0049, IDE0055, IDE1006,
#pragma warning disable SA1004, SA1008, SA1023, SA1028,
#pragma warning disable SA1121, SA1134,
#pragma warning disable SA1201,
#pragma warning disable SA1300, SA1306, SA1307, SA1310, SA1313,
#pragma warning disable SA1500, SA1505, SA1507,
#pragma warning disable SA1600, SA1601, SA1604, SA1605, SA1611, SA1615, SA1649,

namespace Pincushion {
using System;
using System.Runtime.InteropServices;

public unsafe partial class Ffi {
#if IOS
    private const string RustLib = "pincushion.framework/pincushion";
#else
    private const string RustLib = "pincushion";
#endif
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_float_t {
    public float * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_size_t {
    public UIntPtr * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

public unsafe partial class Ffi {
    /// <summary>
    /// - <c>vertices</c>: A flat vec of (x, y, z) vertices.
    /// - <c>triangles</c>: A flat vec of three indices of vertices.
    /// - <c>areas</c>: A vec that will be filled with the areas of each triangle in <c>triangles</c>.
    /// This must be the same length as <c>triangles.len() / 3</c>.
    ///
    /// Returns: The total area.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    float get_areas (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles,
        Vec_float_t * areas);
}

public unsafe partial class Ffi {
    /// <summary>
    /// - <c>total_area</c>: The total area of the triangles in square meters. See: <c>get_areas(vertices, triangles)</c> and <c>get_areas_in_place(vertices, triangles, areas)</c>
    /// - <c>points_per_m</c>: The number of points per square meter.
    ///
    /// Returns: The number of points to be sampled.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    UIntPtr get_num_points (
        float total_area,
        float points_per_m);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Sample random points in a mesh and generate a single mesh compose of icosahedrons.
    ///
    /// - <c>vertices</c>: A flat vec of (x, y, z) vertices.
    /// - <c>triangles</c>: A flat vec of three indices of vertices.
    /// - <c>areas</c>: The area of each triangle. See: <c>get_areas(vertices, triangles, areas)</c>
    /// - <c>total_area</c>: The total area.
    /// - <c>radius</c>: The radius of each icosahedron.
    /// - <c>points</c>: A pre-defined slice of vertices that will be filled with points. The size can differ from <c>triangles</c> and <c>areas</c>.
    /// This will be filled with the sampled points.
    /// This must be defined on the other side of the FFI boundary.
    /// To get the expected size of <c>points</c>, call <c>get_areas(vertices, triangles, areas)</c> followed by <c>get_num_points(total_area, points_per_m)</c>
    /// - <c>ico_vertices</c> The vertices of *all* icosahedrons in the mesh. Expected size: <c>points.len() * 12</c>.
    /// - <c>ico_triangles</c> The triangle indices of *all* icosahedrons in the mesh. Expected size: <c>points.len() * 20</c>.
    /// - <c>ico_uvs</c> The UVs of the vertices of *all* icosahedrons in the mesh. Expected size: <c>points.len() * 2</c>.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void points_to_icosahedrons (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles,
        Vec_float_t /*const*/ * areas,
        float total_area,
        float radius,
        Vec_float_t * points,
        Vec_float_t * ico_vertices,
        Vec_size_t * ico_triangles,
        Vec_float_t * ico_uvs);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Sample random points on the mesh.
    ///
    /// - <c>vertices</c>: A flat vec of (x, y, z) vertices.
    /// - <c>triangles</c>: A flat vec of three indices of vertices.
    /// - <c>areas</c>: The area of each triangle. See: <c>get_areas(vertices, triangles, areas)</c>
    /// - <c>total_area</c>: The total area.
    /// - <c>points</c>: A pre-defined slice of vertices that will be filled with points. The size can differ from <c>triangles</c> and <c>areas</c>.
    /// This will be filled with the sampled points.
    /// This must be defined on the other side of the FFI boundary.
    /// To get the expected size of <c>points</c>, call <c>get_areas(vertices, triangles, areas)</c> followed by <c>get_num_points(total_area, points_per_m)</c>
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void sample_points (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t /*const*/ * triangles,
        Vec_float_t /*const*/ * areas,
        float total_area,
        Vec_float_t * points);
}

public unsafe partial class Ffi {
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void sample_triangles (
        Vec_size_t /*const*/ * triangles,
        Vec_float_t /*const*/ * areas,
        float total_area,
        Vec_size_t * sampled_triangles);
}

public unsafe partial class Ffi {
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void set_points_from_sampled_triangles (
        Vec_float_t /*const*/ * vertices,
        Vec_size_t * sampled_triangles,
        Vec_float_t * points);
}


} /* Pincushion */
