/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#pragma warning disable IDE0044, IDE0049, IDE0055, IDE1006,
#pragma warning disable SA1004, SA1008, SA1023, SA1028,
#pragma warning disable SA1121, SA1134,
#pragma warning disable SA1201,
#pragma warning disable SA1300, SA1306, SA1307, SA1310, SA1313,
#pragma warning disable SA1500, SA1505, SA1507,
#pragma warning disable SA1600, SA1601, SA1604, SA1605, SA1611, SA1615, SA1649,

namespace Pincushion {
using System;
using System.Runtime.InteropServices;

public unsafe partial class Ffi {
#if IOS
    private const string RustLib = "pincushion.framework/pincushion";
#else
    private const string RustLib = "pincushion";
#endif
}

public unsafe partial class Ffi {
    /// <summary>
    /// Returns the number of points to be sampled.
    ///
    /// - <c>total_area</c>: The total area of the triangles in square meters. See: [<c>set_area</c>]
    /// - <c>points_per_m</c>: The number of points per square meter. The mesh's unit of measurement is assumed to be meters.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    UIntPtr get_num_points (
        float total_area,
        float points_per_m);
}

/// <summary>
/// An FFI-safe (x, y, z) vector.
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 12)]
public unsafe struct Vec3_t {
    public float x;

    public float y;

    public float z;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_Vec3_t {
    public Vec3_t * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// Indices of three vertices that comprise a triangle in a mesh.
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Triangle_t {
    public UIntPtr a;

    public UIntPtr b;

    public UIntPtr c;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_Triangle_t {
    public Triangle_t * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// A mesh has vertices, triangles, and normals.
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 72)]
public unsafe struct Mesh_t {
    /// <summary>
    /// The (x, y, z) vertices of the mesh.
    /// </summary>
    public Vec_Vec3_t vertices;

    /// <summary>
    /// (x, y, z) groups of indices of <c>vertices</c>, comprising triangles.
    /// </summary>
    public Vec_Triangle_t triangles;

    /// <summary>
    /// (x, y, z) normal directional vectors.
    /// </summary>
    public Vec_Vec3_t normals;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_float_t {
    public float * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// The surface area of a mesh and of each of its triangles.
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 32)]
public unsafe struct Area_t {
    /// <summary>
    /// The total surface area of the mesh.
    /// </summary>
    public float total_area;

    /// <summary>
    /// The area of each triangle in the mesh.
    /// </summary>
    public Vec_float_t areas;
}

public unsafe partial class Ffi {
    /// <summary>
    /// Sample random points on the mesh.
    /// Requires the <c>ffi</c> feature.
    ///
    /// - <c>mesh</c> The source [<c>Mesh</c>].
    /// - <c>area</c>: The [<c>Area</c>] of the mesh.
    /// - <c>sampled_points</c>: (x, y, z) sampled points.
    /// - <c>sampled_normals</c>: Normal directional vectors, one per sampled point. This must be the same length as <c>sampled_points</c>.
    /// - <c>seed</c>: A random seed used for sampling.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void sample_points (
        Mesh_t /*const*/ * mesh,
        Area_t /*const*/ * area,
        Vec_Vec3_t * sampled_points,
        Vec_Vec3_t * sampled_normals,
        UInt64 seed);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Set the triangles at which points can be sampled.
    /// This is useful for deformable meshes in situations where the positions will change but
    /// not the triangles we want to derive positions from.
    /// Requires the <c>ffi</c> feature.
    ///
    /// - <c>mesh</c> The source [<c>Mesh</c>].
    /// - <c>area</c>: The [<c>Area</c>] of the mesh.
    /// - <c>sampled_triangles</c>: A pre-defined slice of triangles that will be set in this function.
    /// The length must equal number of points that will be sampled.
    /// - <c>seed</c>: A random seed used for sampling.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void sample_triangles (
        Mesh_t /*const*/ * mesh,
        Area_t /*const*/ * area,
        Vec_Triangle_t * sampled_triangles,
        UInt64 seed);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Set the values of an existing [<c>Area</c>].
    /// Requires the <c>ffi</c> feature.
    ///
    /// - <c>mesh</c> The source mesh.
    /// - <c>scale</c> The uniform scale of the mesh.
    /// - <c>area</c>: The [<c>Area</c>] of the mesh.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void set_area (
        Mesh_t /*const*/ * mesh,
        float scale,
        Area_t * area);
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_size_t {
    public UIntPtr * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

/// <summary>
/// Same as [<c>Vec<T></c>][<c>rust::Vec</c>], but with guaranteed <c>#[repr(C)]</c> layout
/// </summary>
[StructLayout(LayoutKind.Sequential, Size = 24)]
public unsafe struct Vec_uint32_t {
    public UInt32 * ptr;

    public UIntPtr len;

    public UIntPtr cap;
}

public unsafe partial class Ffi {
    /// <summary>
    /// Convert <c>mask_indices</c> (see [<c>set_mask_indices</c>]) to <c>mask</c>, a vec of 0s and 1s.
    /// Requires the <c>ffi</c> feature.
    ///
    /// - <c>mask_indices</c> is a  randomly shuffled vec of indices of vertices.
    /// - <c>factor</c> is a value between 0. and 1. The number of "true" values will be <c>mask.len() * factor</c>.
    /// - <c>mask</c> is a vec of u32s because that's what the GPU wants. It must be the same length as <c>mask_indices</c>.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void set_mask (
        float factor,
        Vec_size_t /*const*/ * mask_indices,
        Vec_uint32_t * mask);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Apply a "mask" to filter out some sampled points.
    /// Requires the <c>ffi</c> feature.
    ///
    /// <c>mask_indices</c> must be the same length as the number of sampled points.
    /// To do this in a way that is visually appealing, <c>set_mask_indices</c> is called to:
    ///
    /// - Get the indices of each point (i.e. <c>[0, 1, 2, ...]</c>)
    /// - Shuffle those indices. <c>seed</c> is the random seed.
    /// - Copy the shuffled indices into <c>mask_indices</c>.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void set_mask_indices (
        Vec_size_t * mask_indices,
        UInt64 seed);
}

public unsafe partial class Ffi {
    /// <summary>
    /// Apply a transform matrix to transform sampled points (modify its position and rotation).
    ///
    /// Unity has two built-in ways to do the same operation, but they are slower than Pincushion:
    ///
    /// - <c>Transform.TransformPoint(Vector3)</c> is definitely slower because it's not a bulk operation.
    /// - <c>Transform.TransformPoints(Span<Vector3>)</c> is *probably* slower because it casts each float (f32) to a double (f64) and back again.
    /// This function doesn't perform that cast because it assumes that you won't continuously do math on its output,
    /// and therefore there's no need to worry about precision problems.
    ///
    /// - <c>matrix</c>: A 4x4 transform matrix. The length is assumed to always be 16.
    /// - <c>points</c>: The points that will be transformed.
    /// </summary>
    [DllImport(RustLib, ExactSpelling = true)] public static unsafe extern
    void transform_points (
        Vec_float_t /*const*/ * matrix,
        Vec_Vec3_t * points);
}


} /* Pincushion */
