name: 'Build'
description: 'Build the native pincushion library.'
inputs:
  library:
    required: true
    description: 'The library filename.'

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: cargo build
      shell: bash
      working-directory: pincushion
      run: cargo build --release
    - name: mv, diff, commit, push
      shell: bash
      run: |
        dest=com.mit.pincushion/Runtime/${{ inputs.library }}

        mv pincushion/target/release/${{ inputs.library }} $dest

        if [[ $(git diff --exit-code $dest) -eq 1 ]]; then
          git add $dest
          git commit -m"Rebuilt ${{ inputs.library }}" 
          git push
        fi
