name: 'Build'
description: 'Build the native pincushion library.'
inputs:
  library:
    required: true
    description: 'The library filename.'
outputs:
  dest: 
    value: com.mit.pincushion/Runtime/${{ inputs.library }}
    description: "Destination path of the library."

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: cargo build
      shell: bash
      working-directory: pincushion
      run: cargo build --release
    - name: mv
      shell: bash
      run: mv pincushion/target/release/${{ inputs.library }} ${{ outputs.dest }}
    - name: diff, commit, push
      shell: bash
      run: |
        if [[ $(git diff --exit-code ${{ outputs.dest }} -eq 1 ]]; then
          git add ${{ outputs.dest }}
          git commit -m"Rebuilt ${{ inputs.library }}" 
          git push
        fi
